import { Program, Transformation, FAQItem, Step } from "./types";

export const PROGRAMS_DATA: Program[] = [
  {
    id: "workout-program",
    titleEn: "WORKOUT PROGRAM",
    titleAr: "برنامج التدريب",
    subtitleEn: "Workout Program + Custom Advice",
    subtitleAr: "برنامج تدريبي + نصائح مخصصة",
    icon: "Dumbbell",
    bgImage: "https://d.top4top.io/p_38358x7p31.png",
    price: "$99",
    originalPrice: "$500",
    featuresEn: [
      "Diet Plan: Detailed Diet Plan + Basic Supplement Plan",
      "Workout Program: Detailed Workout Program. Get to the Next Level",
      "Advanced Supplement Plan: Bodybuilding Game Changer"
    ],
    featuresAr: [
      "خطة النظام الغذائي: خطة نظام غذائي مفصلة + خطة مكملات أساسية",
      "برنامج التدريب: برنامج تدريبي مفصل. انتقل إلى المستوى التالي",
      "خطة المكملات المتقدمة: مغير اللعبة في كمال الأجسام"
    ]
  }
];

export const TRANSFORMATIONS_DATA: Transformation[] = [
  {
    id: "t1",
    name: "KMPRANKS",
    beforeImg: "https://iili.io/CYuH7af.png",
    afterImg: "https://iili.io/CYudHqF.png",
    durationEn: "12 Weeks",
    durationAr: "١٢ أسبوعًا",
    tagEn: "ALL NATURAL - FAMOUS YOUTUBER",
    tagAr: "طبيعي بالكامل - يوتيوبر شهير",
    descriptionEn: "1 Program - All Natural transformation, gaining lean muscle mass while shredding body fat.",
    descriptionAr: "برنامج واحد - تحول طبيعي بالكامل، واكتساب كتلة عضلية صافية أثناء حرق دهون الجسم."
  },
  {
    id: "t2",
    name: "VEGAN ATHLETE",
    beforeImg: "https://iili.io/CYT6uZQ.png",
    afterImg: "https://iili.io/CYTizLQ.png",
    durationEn: "12 Weeks",
    durationAr: "١٢ أسبوعًا",
    tagEn: "100% VEGAN - ALL NATURAL",
    tagAr: "نباتي ١٠٠٪ - طبيعي بالكامل",
    descriptionEn: "Incredible lean mass building on a fully plant-based customized nutrition protocol.",
    descriptionAr: "بناء كتلة عضلية مذهل بناءً على بروتوكول تغذية نباتي بالكامل ومخصص."
  },
  {
    id: "t3",
    name: "YOUSEF SABRY",
    beforeImg: "https://iili.io/CYuULxV.png",
    afterImg: "https://iili.io/CYuPIa9.png",
    durationEn: "10 Weeks",
    durationAr: "١٠ أسابيع",
    tagEn: "10 WEEKS TRANSFORM",
    tagAr: "تحول في ١٠ أسابيع",
    descriptionEn: "Massive conditioning and muscle density improvements with strict carbohydrate cycling.",
    descriptionAr: "تحسن هائل في التنشيف وكثافة العضلات مع تدوير الكربوهيدرات الصارم."
  },
  {
    id: "t4",
    name: "MOHAMAD MAKARI",
    beforeImg: "https://iili.io/CYu7DW7.png",
    afterImg: "https://iili.io/CYuYXXS.png",
    durationEn: "24 Weeks",
    durationAr: "٢٤ أسبوعًا",
    tagEn: "2 Programs - Ultimate Shred",
    tagAr: "برنامجان - التنشيف النهائي",
    descriptionEn: "Complete lifestyle and body recomposition over two consecutive programs.",
    descriptionAr: "إعادة تركيب الجسم بالكامل وتغيير نمط الحياة عبر برنامجين متتاليين."
  }
];

export const STEPS_DATA: Step[] = [
  {
    number: 1,
    titleEn: "SUBMISSION",
    titleAr: "تقديم الطلب",
    descEn: "Fill the form and upload Your pictures.",
    descAr: "املأ النموذج وارفع صورك القياسية.",
    icon: "SquarePen"
  },
  {
    number: 2,
    titleEn: "RECEIVE PROGRAM",
    titleAr: "استلام البرنامج",
    descEn: "Wait the duration needed to have Dahab Fit customize your entire program.",
    descAr: "انتظر المدة اللازمة ليقوم كوتش دهب بتخصيص برنامجك بالكامل.",
    icon: "FileText"
  },
  {
    number: 3,
    titleEn: "FOLLOW PROGRAM",
    titleAr: "اتباع البرنامج",
    descEn: "Follow your diet and workout plan.",
    descAr: "اتبع خطتك الغذائية والتدريبية بدقة.",
    icon: "Dumbbell"
  },
  {
    number: 4,
    titleEn: "FOLLOW UP",
    titleAr: "المتابعة",
    descEn: "Send Dahab Fit any concerns or questions you might have regarding the plan.",
    descAr: "أرسل لكوتش دهب أي مخاوف أو استفسارات قد تكون لديك بشأن الخطة.",
    icon: "MailOpen"
  },
  {
    number: 5,
    titleEn: "RESULTS",
    titleAr: "النتائج والتميز",
    descEn: "Look better within 12 weeks!",
    descAr: "احصل على أفضل شكل لجسمك في غضون ١٢ أسبوعًا!",
    icon: "Trophy"
  }
];

export const FAQS_DATA: FAQItem[] = [
  {
    id: "faq-1",
    questionEn: "WHO NEEDS THIS PROGRAM?",
    questionAr: "من يحتاج إلى هذا البرنامج؟",
    answerEn: "Anyone trying to improve his lifestyle, get healthier, lose weight, or gain muscle. No matter your starting level, everything is customized specifically for you.",
    answerAr: "أي شخص يحاول تحسين نمط حياته، أو التمتع بصحة أفضل، أو إنقاص الوزن، أو اكتساب العضلات. بغض النظر عن مستواك البدني الحالي، يتم تفصيل كل شيء خصيصًا لك."
  },
  {
    id: "faq-2",
    questionEn: "IS THIS ONLY FOR BODYBUILDERS?",
    questionAr: "هل هذا البرنامج للاعبي كمال الأجسام فقط؟",
    answerEn: "No, this program is designed for everyone—from corporate professionals and busy parents to competitive athletes and fitness models who want elite-level results.",
    answerAr: "لا، هذا البرنامج مصمم للجميع — من موظفي الشركات والآباء المشغولين إلى الرياضيين المحترفين وعارضي اللياقة البدنية الذين يبحثون عن نتائج ممتازة."
  },
  {
    id: "faq-3",
    questionEn: "IS THE PROGRAM HARD TO FOLLOW? I HAVE A ROUGH WORK/SCHOOL SCHEDULE!",
    questionAr: "هل يصعب اتباع البرنامج؟ لدي جدول عمل/دراسة مزدحم وجدول صعب!",
    answerEn: "All meal plans and workout splits are formulated around your daily lifestyle, profession, and schedule. We work together to ensure it is highly sustainable.",
    answerAr: "يتم صياغة جميع خطط الوجبات وتقسيمات التمارين حول نمط حياتك اليومي ومهنتك وجدولك الزمني. نحن نعمل معًا لضمان استدامته العالية وسهولته."
  },
  {
    id: "faq-4",
    questionEn: "HOW LONG DOES IT TAKE TO MAKE THE PROGRAM?",
    questionAr: "كم من الوقت يستغرق إعداد وتصميم البرنامج المخصص لي؟",
    answerEn: "It takes approximately 5 to 7 business days to complete the physical, scientific analysis of your questionnaire and pictures, and draft your tailored plan.",
    answerAr: "يستغرق الأمر ما يقرب من ٥ إلى ٧ أيام عمل لإكمال التحليل العلمي والبدني للاستبيان الخاص بك والصور، وصياغة خطتك المخصصة."
  },
  {
    id: "faq-5",
    questionEn: "WHAT IF I HAVE QUESTIONS WHEN I RECEIVE THE PLAN?",
    questionAr: "ماذا لو كانت لدي أسئلة أو استفسارات فور استلامي للخطة؟",
    answerEn: "You will have direct messaging/email access to check-ins. You can write your questions, and you will receive clarifications and modifications directly.",
    answerAr: "سيكون لديك وصول مباشر للدردشة/البريد الإلكتروني لإرسال تحديثاتك. يمكنك كتابة أسئلتك، وستتلقى التوضيحات والتعديلات اللازمة مباشرة."
  }
];

export const DICTIONARY = {
  en: {
    brandName: "DAHAB FIT",
    home: "HOME",
    whoIsDurrah: "ABOUT DAHAB FIT",
    transformations: "TRANSFORMATIONS",
    services: "SERVICES",
    videoConsultation: "VIDEO CONSULTATION",
    recipeBook: "The Million Dollar Book",
    contact: "CONTACT",
    olympianSub: "ELITE PERFORMANCE COACHING",
    middleEastSelling: "The Middle East's #1 Selling Online Coach",
    buyNow: "BUY NOW",
    topTransformations: "TOP TRANSFORMATION CLIENTS",
    changeLifeNow: "CHANGE YOUR LIFE NOW!",
    changingLivesTV: "Dietary supplements are the reason for changing people's lives.",
    mediaParagraph1: "Being a worldwide top professional contender in the fitness industry, with 15 years of experience, and a record of over 12,000 *customized programs* made in the last three years alone, it's time you make a change, because your wellness deserves the best.",
    mediaParagraph2: "The program will consist of a 12 week diet plan, along with a complete workout and supplement program to follow to achieve the physique and shape you have always wanted.",
    mediaParagraph3: "Have doubts? Click below and check out the transformations, the testimonials, and what some top celebrities had to say.",
    buyTheProgram: "BUY THE PROGRAM",
    howItWorks: "HOW IT WORKS",
    faqTitle: "FREQUENTLY ASKED QUESTIONS",
    changeLifeToday: "CHANGE YOUR LIFE TODAY!",
    startTodaySub: "START YOUR",
    startTodayMain: "PROGRAM TODAY",
    checkHundredsTransformations: "CHECK OUT HUNDREDS OF TRANSFORMATIONS",
    transformBodyNow: "TRANSFORM YOUR BODY NOW!",
    statsDescription: "Your best self doesn't need luck... it needs a plan.\nAt DahabFit, we analyze and test the best training and nutrition methods used by elite athletes, then turn them into practical programs that fit your daily life, whether your goal is to build muscle, lose fat, or improve your health and performance.",
    coachingSince: "PROVEN DAHAB METHOD",
    programsMade: "ELITE ATHLETES ANALYZED",
    publishedTransformations: "DAYS OF TRANSFORMATION",
    followDurrah: "FOLLOW DAHAB FIT",
    quickLinks: "QUICK LINKS",
    terms: "Terms and Conditions",
    customizedPrograms: "Customized Programs",
    arabicToggle: "عربي",
    englishToggle: "English",
    watchVideo: "Watch on YouTube",
    before: "BEFORE",
    after: "AFTER",
    formName: "Full Name",
    formEmail: "Email Address",
    formWeight: "Current Weight (kg)",
    formHeight: "Height (cm)",
    formAge: "Age",
    formGoal: "Fitness Goal",
    formGoalGain: "Build Muscle",
    formGoalShred: "Lose Fat / Shred",
    formGoalHealth: "Improve General Health",
    formPhotos: "Upload Current Photos (Front / Back / Side)",
    formSubmit: "SUBMIT APPLICATION & ORDER",
    selectPlan: "Select Your Plan",
    orderTitle: "Start Your Custom Elite Program",
    close: "Close",
    contactTitle: "Get In Touch",
    contactSub: "Have questions about our programs? Contact our support team.",
    contactSuccess: "Thank you! Your message has been received. Our team will get back to you within 24 hours.",
    sendMessage: "Send Message",
    bookConsultation: "Book VIP Video Consultation",
    consultationSub: "Schedule a private 30-minute 1-on-1 video call directly with Dahab Fit.",
    consultationSuccess: "Success! Your video consultation slot is reserved. We will email you the secure link.",
    recipeBookTitle: "The Million Dollar Book",
    recipeBookSub: "The ultimate blueprint for transformation: nutrition, supplements, and lifestyle protocols.",
    recipeBookDownload: "Download The Million Dollar Book (PDF)",
    downloadSuccess: "Download started! Enjoy the recipes.",
    whoIsDurrahTitle: "Who is Coach Dahab?",
    whoIsDurrahP1: "Coach Dahab is a world-renowned fitness expert, professional coach, and the Middle East's most successful online fitness and bodybuilding coach.",
    whoIsDurrahP2: "With over 15 years of elite training, Coach Dahab combines science-based nutrition with high-performance training methods to deliver undeniable results. He has helped over 16,000 clients worldwide break boundaries and transform their physiques.",
    compareText: "Drag slider to compare",
  },
  ar: {
    brandName: "دهب فيت",
    home: "الرئيسية",
    whoIsDurrah: "عن دهب فيت",
    transformations: "التحولات",
    services: "الخدمات",
    videoConsultation: "استشارة فيديو",
    recipeBook: "The Million Dollar Book",
    contact: "اتصل بنا",
    olympianSub: "تدريب لياقة بدنية احترافي",
    middleEastSelling: "المدرب الإلكتروني الأول مبيعًا في الشرق الأوسط",
    buyNow: "اشترِ الآن",
    topTransformations: "أبرز تحولات المتدربين",
    changeLifeNow: "غير حياتك الآن!",
    changingLivesTV: "المكملات الغذائية هي السبب في تغيير حياة الناس.",
    mediaParagraph1: "بصفتي منافسًا محترفًا رائدًا عالميًا في صناعة اللياقة البدنية، مع خبرة ١٥ عامًا، وسجل حافل بأكثر من ١٢,٠٠٠ برنامج مخصص تم إعداده في السنوات الثلاث الأخيرة وحدها، فقد حان الوقت لإحداث التغيير، لأن صحتك تستحق الأفضل.",
    mediaParagraph2: "سيتكون البرنامج من خطة غذائية لمدة ١٢ أسبوعًا، إلى جانب برنامج تدريب ومكملات كامل لمساعدتك في تحقيق الشكل الذي طالما رغبت فيه.",
    mediaParagraph3: "لديك شكوك؟ انقر أدناه واطلع على التحولات، وشهادات المتدربين، وما قاله كبار المشاهير.",
    buyTheProgram: "اشترِ البرنامج",
    howItWorks: "كيف يعمل البرنامج",
    faqTitle: "الأسئلة الشائعة ومخاوف المتدربين",
    changeLifeToday: "ابدأ بتغيير حياتك اليوم!",
    startTodaySub: "ابدأ برنامجك",
    startTodayMain: "المخصص اليوم",
    checkHundredsTransformations: "شاهد مئات التحولات المذهلة",
    transformBodyNow: "حول جسمك الآن!",
    statsDescription: "أفضل نسخة منك لا تحتاج إلى الحظ... بل تحتاج إلى خطة.\nفي دهب فيت، نقوم بتحليل واختبار أفضل أساليب التدريب والتغذية التي يستخدمها نخبة الرياضيين، ثم نحولها إلى برامج عملية تناسب حياتك اليومية، سواء كان هدفك بناء العضلات، خسارة الدهون، أو تحسين صحتك وأدائك.",
    coachingSince: "طريقة دهب المثبتة",
    programsMade: "نخبة من الرياضيين تم تحليل أدائهم",
    publishedTransformations: "يوم من التحول",
    followDurrah: "تابع كوتش دهب فيت",
    quickLinks: "روابط سريعة",
    terms: "الشروط والأحكام",
    customizedPrograms: "البرامج المخصصة",
    arabicToggle: "عربي",
    englishToggle: "English",
    watchVideo: "شاهد على يوتيوب",
    before: "قبل",
    after: "بعد",
    formName: "الاسم الكامل",
    formEmail: "البريد الإلكتروني",
    formWeight: "الوزن الحالي (كجم)",
    formHeight: "الطول (سم)",
    formAge: "العمر",
    formGoal: "هدفك الرياضي",
    formGoalGain: "بناء وتضخيم العضلات",
    formGoalShred: "حرق الدهون والتنشيف",
    formGoalHealth: "تحسين اللياقة والصحة العامة",
    formPhotos: "ارفع صورك الحالية (أمامية / خلفية / جانبية)",
    formSubmit: "تقديم الطلب والاشتراك",
    selectPlan: "اختر خطتك التدريبية",
    orderTitle: "ابدأ برنامج النخبة المخصص لك",
    close: "إغلاق",
    contactTitle: "تواصل معنا",
    contactSub: "لديك استفسار بخصوص البرامج؟ تواصل مع فريق الدعم الفني.",
    contactSuccess: "شكرًا لك! تم استلام رسالتك بنجاح. وسيقوم فريق الدعم بالرد عليك في غضون ٢٤ ساعة.",
    sendMessage: "إرسال الرسالة",
    bookConsultation: "احجز استشارة فيديو VIP",
    consultationSub: "احجز مكالمة فيديو خاصة 1-on-1 لمدة ٣٠ دقيقة مباشرة مع كوتش دهب فيت.",
    consultationSuccess: "تم الحجز بنجاح! تم حجز موعد استشارتك الخاصة، وسنرسل لك الرابط الآمن عبر البريد الإلكتروني.",
    recipeBookTitle: "The Million Dollar Book",
    recipeBookSub: "المخطط النهائي للتحول البدني المتكامل: التغذية والمكملات وأسلوب الحياة الرياضي.",
    recipeBookDownload: "تحميل كتاب The Million Dollar Book (PDF)",
    downloadSuccess: "بدأ التحميل الآن! بالهناء والشفاء.",
    whoIsDurrahTitle: "من هو كوتش دهب؟",
    whoIsDurrahP1: "كوتش دهب هو خبير لياقة بدنية وبطل ذو شهرة واسعة، وأحد أنجح مدربي اللياقة البدنية والكمال الأجسام عبر الإنترنت في الشرق الأوسط.",
    whoIsDurrahP2: "مع أكثر من ١٥ عامًا من التدريب الاحترافي، يجمع كوتش دهب بين التغذية القائمة على العلم وأساليب التدريب الشاقة لتقديم نتائج مضمونة لا تقبل الشك. ساعد أكثر من ١٦,٠٠٠ متدرب حول العالم في تحطيم القيود وتحقيق أجسام أحلامهم.",
    compareText: "اسحب شريط التمرير للمقارنة"
  }
};
